#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================
# MODIFY A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

config="$install_dir/.env"
ynh_backup_if_checksum_is_different "$install_dir/CONFIG_FILE"

ynh_replace --match="$old_domain$old_path" --replace="$new_domain$new_path" --file="$config"

ynh_store_file_checksum "$config"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
